name: flutter_lpos
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add WebView plugin
  webview_flutter: ^4.4.2

  # Linting package
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
